#!/bin/sh -el
VERSION=${VERSION:-0.$(date +%Y%m%d%H%M)}

if ! test -t 1; then
  grunt_opts="--no-color"
fi

while test $# -gt 0; do
  case "$1" in
    -v)
      VERSION=$2;;
    --ci)
      ci=true;;
  esac
  shift
done

grunt $grunt_opts validator
grunt --no-color --stack --verbose test
if [ -z "$ci" ]; then
  grunt $grunt_opts sonar
else
  grunt $grunt_opts sonar-ci
fi

rm -f debian/changelog
dch --create --controlmaint --package housing-data -v $VERSION ""
./debian/rules clean
./debian/rules build
fakeroot ./debian/rules binary OUTDIR=.
