#!/bin/sh -el
VERSION=${VERSION:-0.$(date +%Y%m%d%H%M)}

while test $# -gt 0; do
  case "$1" in
    -v)
      VERSION=$2;;
    --ci)
      ci=true;;
  esac
  shift
done

npm run validator
npm run test
if [ -n "$ci" ]; then
  sonar-scanner
fi

rm -f debian/changelog
dch --create --controlmaint --package housing-data -v $VERSION ""
./debian/rules clean
./debian/rules build
fakeroot ./debian/rules binary OUTDIR=.
