application:
  name: housingdata

cpi:
  graceperiod: PT12H
  source:
    url: https://www.ons.gov.uk/generator?format=csv&uri=/economy/inflationandpriceindices/timeseries/d7bt/mm23
  update:
    crontab: '0 * * * *'
    retryinterval: 10000

couch:
  url: http://localhost:5984/

s3:
  enabled: false
  region: ''
  target: ''
