#!/bin/bash
set -eu
dir="$(dirname $0)"
if [ "$dir" != . ]; then
  cd "$dir"
fi
remote=$(jq -r .env.default.db < .couchapprc)
if ! cmp --quiet \
  <(curl -s $remote/_design/rpz |jq -S 'del(._rev)') \
  <(couchapp push --export | \
    jq -S 'del(._rev) | del(._attachments)') ; then
  echo "Updating design document."
  couchapp push --docid _design/rpz
else
 echo "Not changed"
fi
