#!/bin/sh
# postinst script for housing-data
#
# see: dh_installdeb(1)

set -e

configure() {
  # Set-up housing-data user
  adduser \
     --quiet \
     --system \
     --home /opt/housing-data \
     --no-create-home \
     --shell /bin/bash \
     --group \
     --gecos "Housing-data" \
     housing-data

  /opt/housing-data/couch/push | logger -t housing-data
}

case "$1" in
    configure)
      configure
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
