#!/bin/bash
. /etc/profile
set -eu
dir="$(dirname $0)"
if [ "$dir" != . ]; then
  cd "$dir"
fi
remote=http://localhost:5984/ons
couchdb_user=${housing_data_couchdb_user-${couchdb_user-}}
couchdb_password=${housing_data_couchdb_password-${couchdb_password-}}
if [ -n "$couchdb_user" ] && [ -n "$couchdb_password" ]; then
  proto=${remote%%://*}
  rest=${remote#*//}
  remote="${proto}://${couchdb_user}:${couchdb_password}@${rest}"
fi
echo "Updating design document."
../node_modules/.bin/couchdb-push "$remote" .
echo "Updating security document."
curl -sSf \
  -X PUT \
  -H 'Content-Type: application/json' \
  -d '{}' \
  $remote/_security
